apps/Trips/urls.py
from django.conf.urls import url
from views import dashboard, addTrip, destination, join, logout
app_name= "trips"
urlpatterns = [
    url(r'^$', dashboard, name='dashboard'),
    url(r'^addTrip$', addTrip, name='addTrip'),
    url(r'^destination/(?P<id>\d+)/(?P<owner_id>\d+)$', destination, name='destination'),
    url(r'^join/(?P<id>\d+)$', join, name='join'),
    url(r'^logout$', logout, name='logout')
]

blackBeltDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.loginAndRegistration.urls', namespace="loginAndRegistration")),
    url(r'^dashboard/', include('apps.Trips.urls', namespace="Trips")),
]

apps/Trips/models.py
from __future__ import unicode_literals
from django.db import models
from ..loginAndRegistration.models import User

class DestinationManager(models.Manager):
    def add_user_to_trip(self,postData):
        flag=False
        errors=[]
        if len(postData['destination'])<1:
            flag=True
            errors.append("Destination cannot be empty!")
        if len(postData['description'])<1:
            flag=True
            errors.append("Description cannot be empty!")
        if postData['datefrom'] < postData['today']:
            flag=True
            errors.append("Travel Date cannot be before today!")
        if postData['dateto']< postData['datefrom']:
            flag=True
            errors.append("End of travel cannot be before the start!")
        # if postData['dateto'].isoformat()>postdata['datefrom'].isoformat():
            # flag=True
            # errors.append("Travel to Date cannot be before Travel From")
        if not flag:
            trip= Destination.objects.create(owner=User.objects.get(id=postData['user']),destination=postData['destination'], description=postData['description'], datefrom=postData['datefrom'], dateto= postData['dateto'])
            Join.objects.create(trip_user=User.objects.get(id=postData['user']), trip_destination=trip)
            return (flag, trip)
        return (flag, errors)

class Destination(models.Model):
    owner= models.ForeignKey(User, related_name="owner")
    destination = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    datefrom= models.DateTimeField(max_length=20)
    dateto= models.DateTimeField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects= DestinationManager()

class Join(models.Model):
	trip_user= models.ForeignKey(User, related_name="tripuser")
	trip_destination = models.ForeignKey(Destination, related_name="tripdestination")
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

apps/Trips/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from datetime import datetime
from django.core.urlresolvers import reverse
from ..loginAndRegistration.models import User
from .models import Destination, Join

def dashboard(request):
    variable=Join.objects.filter(trip_user_id=request.session['user_id'])
    second= Destination.objects.exclude(owner_id=request.session['user_id'])
    for x in variable:
        second=second.exclude(id=x.trip_destination.id)
    third=Destination.objects.filter(owner_id=request.session['user_id'])
    context={
        "destinations": variable,
        "trip_users": second,
        "owner_id": third
    }
    print third
    return render(request, "Trips/dashboard.html",context)

def addTrip(request):
    if request.method=="GET":
        return render(request, 'Trips/addTrip.html')
    if request.method=="POST":
        today=datetime.now()
        datefrom=datetime.strptime(request.POST['datefrom'], '%Y-%m-%d')
        dateto= datetime.strptime(request.POST['dateto'], '%Y-%m-%d')
        postData={
            "user":request.session['user_id'],
            "destination": request.POST['destination'],
            "description": request.POST['description'],
            "datefrom": datefrom,
            "dateto": dateto,
            "today": today,
        }
        results=Destination.objects.add_user_to_trip(postData)
        if results[0]:
            for err in results[1]:
                messages.error(request,err)
            return render(request, 'Trips/addTrip.html')
        return redirect(reverse('Trips:dashboard'))

def destination(request, id, owner_id):
    variable=Join.objects.exclude(trip_user_id=owner_id)
    second=Join.objects.filter(trip_destination_id=id)
    print variable
    print second
    # for x in variable:
        # second=second.exclude()
    context={
        "destinations": Destination.objects.get(id=id),
        "trip_users": second
    }
    return render(request, "Trips/destination.html", context)

def join(request, id):
    user= User.objects.get(id=request.session['user_id'])
    destination=Destination.objects.get(id=id)
    Join.objects.create (trip_user=user, trip_destination=destination)
    print
    return redirect(reverse('Trips:dashboard'))

def logout(request):
    request.session.pop('user_id')
    request.session.pop('name')
    return redirect(reverse("loginAndRegistration:index"))

apps/Trips/templates/trips/addTrip.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Add Trip</title>
    <link rel="stylesheet" href="{% static 'Trips/css/trips.css' %}"media="screen"  charset="utf-8">

</head>
<body>
<div id="wrapper">
    <div id="topright">
        <a href="{% url 'Trips:dashboard' %}">Home</a>
        <a href="{% url 'Trips:logout' %}">Logout</a>
    </div>
    <h1>Add a Trip<h1>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class={{message.tags}} {% endif %}>{{message}}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form action="{%url 'Trips:addTrip' %}" method='post'>
            {% csrf_token %}
            <p><label for="destination">Destination:</label>
            <input type="text" name="destination" class="longer" required></p>
            <p><label for="Description">Description:</label>
            <input type="text" name="description" class="longer"required></p>
            <p><label for="dateto">Travel Date From:</label>
            <input class="datefrom" type="date" name="datefrom" required></p>
            <p><label for="dateto">Travel Date To:</label>
            <input class="dateto" type="date" name="dateto" required></p>
            <p><input type="submit" value="Add"></p>
        </form>
</div>
</body>
</html>

apps/Trips/templates/trips/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Trips</title>
    <link rel="stylesheet" href="{% static 'Trips/css/trips.css' %}"media="screen"  charset="utf-8">
</head>
<body>
    <div id="wrapper">
        <div id="topright">
            <a href="{%url 'Trips:logout'  %}">Logout</a>
        </div>
        <h1>Welcome, {{request.session.name}}</h1>

        <h1>Your Trip Schedules</h1>
        <table>
            <thead>
                <tr>
                <td>Destination</td><td>Travel Start Date</td><td>Travel End Date</td><td>Plan</td>
            </tr>
            </thead>
            <tbody>
                {% for destination in destinations %}
                <tr>
                <td><a href="{% url 'Trips:destination' id=destination.trip_destination_id owner_id=destination.trip_destination.owner.id%}"> {{destination.trip_destination.destination}}</a></td><td>{{destination.trip_destination.datefrom}}</td><td><{{destination.trip_destination.dateto }}</td><td>{{destinaton.trip_destination.description }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <h1>Other User's Travel Plans</h1>
        <table>
            <thead>
                <tr>
                <td>Name</td><td>Destination</td><td>Travel Start Date</td><td>Travel End Date</td><td>Do You Want to Join?</td>
            </tr>
            </thead>
            <tbody>
                {% for trip_user in trip_users %}
                <tr>
                <td><a href="{% url 'Trips:destination' id=trip_user.id owner_id=trip_user.owner.id %}"> {{trip_user.destination}}</a></td><td>{{trip_user.datefrom}}</td><td><{{trip_user.dateto }}</td><td>{{trip_user.description }}</td><td><a href='{% url "Trips:join" id=trip_user.id %}'>Join</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'Trips:addTrip' %}" value="AddTrip">Add Trip </a>
    </div>
</body>
</html>

apps/Trips/templates/trips/destination.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'Trips/css/travelPlans.css' %}"media="screen"  charset="utf-8">
    <title>Destination</title>
</head>
<body>
    <div id="wrapper">
        <div id="topright">
            <a href="{% url 'Trips:dashboard' %}">Home</a>
            <a href="{% url 'Trips:logout' %}">Logout</a>
        </div>
        <h1>Trip Destination</h1>
            <h3>{{destinations.destination}}</h3>
                <p>Planned By: {{destinations.owner.name}}</p>
                <p>Description: {{destinations.description}}</p>
                <p>Travel Date From: {{destinations.datefrom}}</p>
                <p>Trave Date To: {{destinations.dateto}}</p>
            <h3>Other users joining the trip:</h3>



            {% for trip_user in trip_users %}
            {%  if trip_user.trip_user.id != destinations.owner.id %}
                <p>{{trip_user.trip_user.name}}</p>
                {% endif %}
            {% endfor %}

        <a href="{% url 'Trips:addTrip' %}" value="goback">Enter another trip! </a>
    </div>
</body>
</html>