apps/loginAndRegistration/urls.py
from django.conf.urls import url
from views import index, register, login
app_name= "loginAndRegistration"
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^register$', register, name='register'),
    url(r'^login$', login, name='login'),
]

blackBeltDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.loginAndRegistration.urls', namespace="loginAndRegistration")),
    url(r'^dashboard/', include('apps.Trips.urls', namespace="Trips")),
]

apps/loginAndRegistration/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt
import re

NAME_REGEX = re.compile(r'^[a-zA-Z]*$')

class UserManager(models.Manager):
    def UserValidator(self, postData):
        flag=False
        errors=[]
        if len(postData['name']) < 3:
            errors.append("Name must be at least 3 characters!")
            flag=True
        elif not NAME_REGEX.match(postData['name']):
            errors.append("Invalid name!")
            flat=True
        if len(postData['username']) <3:
            flag=True
            errors.append("Username must be at least 3 characters!")
        if len(postData['password'])<8:
            flag=True
            errors.append("Password length is invalid")
        if len(postData['password_confirmation']) < 1:
            errors.append("Confirm password cannot be empty!")
            flag=True
        if postData['password_confirmation'] != postData['password']:
            flag=True
            errors.append("Passwords do not match!")
        if not flag:
            pwhash= bcrypt.hashpw(postData['password'].encode(),bcrypt.gensalt())
            User.objects.create(
                name=postData['name'],
                username=postData['username'],
                password= pwhash )
            user = User.objects.last()
            return (flag, user)
        return (flag, errors)
    def userLogin(self, postData):
        login= User.objects.filter(username=postData['username'])
        if len(login)<1:
            return (False, "User does not exist in database")
        else:
            user= User.objects.get(username=postData['username'])
            password= postData['password'].encode()
            hashed=user.password.encode()
            if bcrypt.hashpw(password, hashed )== hashed and user:
                return (True, user)
            else:
                return (False, "Username and password do not match")

class User(models.Model):
    name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects= UserManager()

apps/loginAndRegistration/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import User
import bcrypt

def index(request):
    print User.objects.all()
    if not 'errors' in request.session:
        request.session['errors']=[]
    return render(request, 'loginAndRegistration/index.html')

def register(request):
    postData= {
        "name":request.POST['name'],
        "username": request.POST['username'],
        "password": request.POST['password'],
        "password_confirmation":request.POST['password_confirmation']
    }
    results= User.objects.UserValidator(postData)
    if results[0]:
        for err in results[1]:
            messages.error(request,err)
        return render (request, 'loginAndRegistration/index.html')
    else:
        request.session['user_id']= results[1].id
        request.session['name']=results[1].name
        return redirect(reverse('Trips:dashboard'))

def login(request):
    postData={
        "username": request.POST['username'],
        "password": request.POST['password']
    }
    results = User.objects.userLogin(postData)
    if results == None:
        messages.error(request, "wrong credentials")
        return redirect(reverse('loginAndRegistration:index'))
    elif results[0]:
        request.session['name']= results[1].name
        request.session['user_id']= results[1].id
        return redirect(reverse("Trips:dashboard"))
    else:
        messages.error(request, results[1])
        return redirect(reverse('loginAndRegistration:index'))

apps/loginAndRegistration/templates/loginAndRegistration/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Login and Registration</title>
    <link rel="stylesheet" href="{% static 'loginAndRegistration/css/loginAndRegistration.css' %}"media="screen"  charset="utf-8">
</head>
<body>
    <div id="wrapper">
        <h1>Login and Registration</h1>
        {% if messages %}
        <ul class="messages">
        {%for message in messages%}
        <li {% if message.tags %} class={{message.tags}} {% endif %}>{{message}}</li>
        {% endfor %}
        </ul>
        {% endif %}
        <h3>Register Below!</h3>
        <form action="{% url 'loginAndRegistration:register' %}" method='post'>
            {% csrf_token %}
            <p> Name: <input class="longer" type='text' name='name' placeholder="cannot contain numbers" required></p>
            <p>Username: <input class="longer" type='text' name='username' placeholder="enter a valid username" required></p>
            <p>Password: <input class="longer" type='password' name='password' placeholder="must be at least 8 characters" required></p>
            <p>Confirm Password: <input class="longer" type='password' name='password_confirmation' placeholder="must be at least 8 characters" required=""></p>
            <input class="submit" type='submit' value='Create User'>
        </form>
        <h3>Already Registered?</h3>
        <form action="{% url 'loginAndRegistration:login' %}" method='post'>
            {% csrf_token %}
            <p>Username: <input class="longer" type='text' name='username'></p>
            <p>Password: <input class="longer" type='password' name='password'></p>
            <input type='submit' value='Login'>
        </form>
    </div>
</body>
</html>